# Generated by Django 3.0.4 on 2020-03-19 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert1', to='main.Experts')),
                ('expert2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert2', to='main.Experts')),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headertype', models.IntegerField()),
                ('headercontent', models.CharField(max_length=200)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Experts')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
